module.exports = 
  babelMapsAddUrl: true
  babelMapsPath: ''
  babelSourcePath: ''
  babelStage: 2
  babelTranspilePath: ''
  blacklistTransformers: []
  createMap: false
  createTargetDirectories: false
  createTranspiledCode: true
  externalHelpers: []
  looseTransformers: []
  moduleLoader: 'common'
  optionalTransformers: []
  stopAtProjectDirectory: false
  supressSourcePathMessages: false
  transpileOnSave: true
  useInternalScanner: false
  whitelistTransformers: []
